vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_annonces:
            uri_prefix: /images/annonces
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
