# config/routes.yaml

# Import routes from the controllers directory
controllers:
    resource: ../src/Controller/
    type: attribute

# Define the delete_user route separately
delete_user:
    path: '/delete/{id}'
    controller: 'App\Controller\UserController::deleteUser'
    methods: ['DELETE']
